Repository Alpha-e-Um/Frontend, pull requests merged in 2024-04, with the labels that each got.

#15 회원탈퇴 페이지 팀 생성 페이지 제작
  src/assets/myPage/Exit.svg
  src/assets/myPage/WithdrawalIcon.svg
  src/components/Card/styles.js
  src/components/MyFavorites/myFavorites.js
  src/components/MyFavorites/styles.js
  src/components/MyInfo/myInfo.js
  src/components/MyInfo/styles.js
  src/components/MyPageSideBar/myPageSideBar.js
  src/components/MyTeam/myTeam.js
  src/components/MyTeamCreate/myTeamCreate.js
  src/components/MyTeamCreate/styled.js
  src/components/WithdrawalModal/styles.js
  src/components/WithdrawalModal/withdrawalModal.js
  src/pages/MyPage/.cph/.styles.js_7941c311d786747aad6ae0ba315e5776.prob
  src/pages/MyPage/myPage.js
  src/pages/MyPage/styles.js
Labels: enhancement

#19 feat: #16/프론트 Docker 및 nginx 설정
  Dockerfile
  default.conf
Labels: enhancement, setting

#23 Feature/#17/git action을 통한 CI/CD 적용
  .github/workflows/react.yml
Labels: deploy, setting

#29 Feature/#28/refactor
  src/App.js
  src/api/axios.js
  src/api/teamAPI.js
  src/api/testDummyData/contestTestData.js
  src/api/testDummyData/memberTestData.js
  src/api/testDummyData/memberTestData3.js
  src/api/testDummyData/memberTestDats2.js
  src/api/testDummyData/myResumeTestData.js
  src/api/testDummyData/myTeamTestData.js
  src/api/testDummyData/supportTestData.js
  src/api/testDummyData/teamTestData.js
  src/api/testDummyData/teamTestData2.js
  src/api/testDummyData/teamTestData3.js
  src/api/userAPI.js
  src/components/MyFavorites/myFavorites.js
  src/components/MyResume/myResume.js
  src/components/MySupport/mySupport.js
  src/components/MyTeam/myTeam.js
  src/components/MyTeamPage/myTeamPage.js
  src/pages/Login/login.js
  src/pages/Main/main.js
  src/pages/MemberSearch/memberSearch.js
  src/pages/TeamSearch/teamSearch.js
Labels: enhancement

#31 fix: #30-네비게이션, 메인 스타일 수정
  public/icons/gatherMember.svg
  public/icons/gatherTeam.svg
  public/icons/manageResume.svg
  src/components/Introduce/styles.js
  src/components/Navigation/navigation.js
  src/components/Navigation/styles.js
  src/components/SubNavigation/subNavigation.js
Labels: enhancement
